[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "SequenceDot"
version = "0.2.1"
description = "A command-line tool for generating k-mer based dotplots from biological sequences"
authors = [
    {name = "Marlies Jilles Francine Goedknegt", email = "marliesgoedknegt@ruc.dk"}
]
license = {text = "GPL-3.0"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "typer",
    "biopython",
    "numpy",
    "matplotlib",
    "tqdm"
]

[project.urls]
Homepage = "https://github.com/MarliesJFrancine/SequenceDot"

[project.scripts]
seqdot = "seqdot.cli:app"

[tool.setuptools.packages.find]
where = ["src"]