[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"


[project]
name = "seqdot"
version = "0.2.0"
description = "A command-line tool for generating k-mer based dotplots from biological sequences"
authors = [
    {name = "Marlies Jilles Francine Goedknegt"}
]
dependencies = [
    "typer",
    "biopython",
    "numpy",
    "matplotlib",
    "tqdm"
]


[project.scripts]
seqdot = "seqdot.cli:app"


[tool.setuptools.packages.find]
where = ["src"]
